---
apiVersion: v1
kind: Service
metadata:
  name: kws
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: kws
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kws
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kws
  template:
    metadata:
      labels:
        app: kws
    spec:        
      containers:
      - name: kws
        image: asia.gcr.io/ai-experiments-332802/kws:v1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
        env:
          - name: PORT
            value: "80"
      nodeSelector:
        cloud.google.com/gke-nodepool: ai-cpu-pool